# Generated by Django 3.2.7 on 2021-11-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pc',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='processor',
            options={'managed': True},
        ),
    ]
