# Generated by Django 3.2.7 on 2021-11-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'PC',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('numb_cores', models.IntegerField()),
                ('freq', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'Processor',
                'managed': False,
            },
        ),
    ]
